/**
 * Cloudflare Worker entrypoint.
 *
 * Wraps the OpenNext-generated handler to add two things it does not provide:
 *
 *   1. The `RenderContainer` Durable Object export. A container binding is only
 *      valid if its class is exported from the same Worker, so it has to be
 *      re-exported here rather than living in its own script.
 *   2. A `scheduled` handler. The cron trigger wakes the render container so
 *      queued jobs are picked up even when no one is visiting the site.
 *
 * `fetch` is delegated to OpenNext untouched — this file adds capabilities, it
 * does not intercept requests.
 */

// Generated by `opennextjs-cloudflare build`; it does not exist until then, so
// there is no type declaration to import.
// @ts-expect-error - resolved at build time from .open-next/worker.js
import openNextHandler from '../.open-next/worker.js';

export { RenderContainer } from './server/cloudflare/render-container';

interface Env {
  RENDER_CONTAINER?: DurableObjectNamespace;
  CONTAINER_TOKEN?: string;
  [key: string]: unknown;
}

type OpenNextHandler = ExportedHandler<Env>;

const handler = openNextHandler as OpenNextHandler;

export default {
  fetch: handler.fetch,

  /**
   * Wake the render container on a schedule.
   *
   * Deliberately fire-and-check rather than fire-and-forget: if the container
   * cannot be reached, that is worth a log line, because the symptom otherwise
   * is renders that silently never start.
   */
  async scheduled(controller, env, ctx): Promise<void> {
    if (!env.RENDER_CONTAINER) {
      console.log('cron: no render container bound, nothing to wake');
      return;
    }

    ctx.waitUntil(
      (async () => {
        const { wakeRenderContainer } = await import('./server/cloudflare/render-client');
        const result = await wakeRenderContainer();

        console.log(
          JSON.stringify({
            event: 'cron.drain',
            cron: controller.cron,
            woken: result.woken,
            detail: result.detail.slice(0, 200),
          }),
        );
      })(),
    );
  },
} satisfies ExportedHandler<Env>;
